version: 2

models:
  - name: fact_rentals
    columns:
      - name: rental_id
        data_type: integer
        tests:
          - unique
          - not_null

      - name: rental_date
        data_type: date

      - name: rental_duration
        data_type: integer

      - name: customer_id
        data_type: integer

      - name: staff_id
        data_type: integer

      - name: film_id
        data_type: integer

      - name: store_id
        data_type: integer

      - name: amount
        data_type: numeric

  - name: dim_film
    columns:
      - name: film_id
        data_type: integer
        tests:
          - unique
          - not_null

      - name: title
        data_type: text

      - name: release_year
        data_type: integer

      - name: rental_duration
        data_type: integer

      - name: rating
        data_type: text

      - name: category
        data_type: text

  - name: dim_customer
    columns:
      - name: customer_id
        data_type: integer
        tests:
          - unique
          - not_null

      - name: full_name
        data_type: text

      - name: email
        data_type: text

      - name: city
        data_type: text

      - name: country
        data_type: text

  - name: dim_store
    columns:
      - name: store_id
        data_type: integer
        tests:
          - unique
          - not_null

      - name: city
        data_type: text

      - name: country
        data_type: text

  - name: dim_staff
    columns:
      - name: staff_id
        data_type: integer
        tests:
          - unique
          - not_null

      - name: full_name
        data_type: text

      - name: email
        data_type: text

  - name: dim_dates
    columns:
      - name: date_day
        data_type: date
        tests:
          - unique
          - not_null

      - name: day_of_week
        data_type: integer

      - name: day_of_month
        data_type: integer

      - name: day_of_year
        data_type: integer

      - name: week_of_year
        data_type: integer

      - name: month_of_year
        data_type: integer

      - name: month_name
        data_type: text

      - name: quarter_of_year
        data_type: integer

      - name: year_number
        data_type: integer